TeamName = {
	"Archon":"Archon.png",
	"Arrow":"Arrow.png",
	"Cis":"CIS.png",
	"AA":"D_Acion Arena.png",
	"Ad":"D_AdFinem.png",
	"A":"D_Alliance.png",
	"Bears":"D_B)ears.png",
	"BH":"d_bheart.png",
	"BM":"D_Broodmothers.png",
	"C9":"D_C9.png",
	"CSW":"D_CantSayWips.png",
	"CDEC":"D_CDEC.png",
	"CG":"D_cluthgamers.png",
	"COL":"D_Col.png",
	"Comanche":"D_Comanche.png",
	"DC":"D_DigitalChaos.png",
	"DW":"D_DooWop.png",
	"Effect":"D_Effect.png",
	"EG":"D_EG.png",
	"EHL":"D_EHOME.Luminous.png",
	"EH":"D_EHOME.png",
	"EHX":"D_EHOME.X.png",
	"EHK":"D_EHOME_Keen.png",
	"EW":"D_EliteWolves.png",
	"Empire":"D_Empire.png",
	"EE":"D_Entity Esports.png",
	"EPG":"D_EPG.png",
	"FL":"D_faceless.png",
	"FF":"D_FantasticFive.png",
	"FDL":"D_Fdl.png",
	"FD":"D_FirstDeparture.png",
	"Fn":"D_Fnatic.png",
	"Friends":"D_Friends.png",
	"FTDA":"D_FTD.A.png",
	"FTDB":"D_FTD.B.png",
	"FTDC":"D_FTD.c.png",
	"Geek":"D_Geek fam.png",
	"Gus":"D_GUS Gaming.png",
	"HF":"D_HappyFeet.png",
	"Horde":"D_Horde.png",
	"HR":"D_HR.png",
	"IG":"d_IG.png",
	"IGV":"D_IG.vitality.png",
	"Infamous":"D_Infamous.png",
	"kp":"D_Kaipi.png",
	"LFY":"D_LGD.Forever Young.png",
	"LGD":"D_LGD.png",
	"Liquid":"D_Liquid.png",
	"LQ":"D_Lq.png",
	"MCE":"D_Midas_Club_Elite.png",
	"MineskiX":"D_Mineski-X.png",
	"Mineski":"D_MINESKI.png",
	"Mith":"D_Mith.png",
	"MVP":"D_MVP.png",
	"N9":"D_Natural_9.png",
	"Navi":"D_Natus_Vincere.png",
	"NBY":"D_Newbee Young.png",
	"NBB":"D_Newbee.boss.png",
	"NB":"D_NEWBEE.png",
	"NG":"D_Next gen.png",
	"NIP":"D_Ninjas in pyjamas.png",
	"NT":"D_Not_Today.png",
	"NP":"D_NP.png",
	"OG":"D_OG.png",
	"PENTA":"D_PENTA Sports.png",
	"PO":"D_planetodd.png",
	"PG":"D_ProdotaGaming.png",
	"Rava":"D_Rave.png",
	"RRQ":"D_Rex_Regum.png",
	"S1":"D_S1 Lykos.png",
	"SS":"D_Sanguine Sharks.png",
	"Secret":"D_Secret.png",
	"SYA":"D_See You Again.Australia.png",
	"SG":"D_SG_e-sports.png",
	"TOT":"D_T.O.O.png",
	"TSHOW":"D_T_show.png",
	"TF":"D_Team Freedom.png",
	"TS":"D_Team Spirit.png",
	"VGJ":"D_Team_VG.J.png",
	"Levithan":"D_TeamLevithan.png",
	"Onyx":"D_TeamOnyx.png",
	"TNC":"D_Tncproteam.png",
	"Vega":"D_Vega.png",
	"VG":"D_VICI_Gaming.png",
	"VP":"D_VP.png",
	"Wanted":"D_WanteD.png",
	"WAY":"D_WeAreYoung.png",
	"WG":"D_WG.png",
	"Wheel":"D_Wheel Whreck While Whistling.jpg",
	"WF":"D_White Fries Gaming.png",
	"Wings":"D_Wings.png",
	"Xctn":"D_XctN.png",
	"DK":"DK.png",
	"Invation":"InvationMufc.png",
	"LGDINT":"LCDINT.png",
	"malaysia":"malaysia.png",
	"mouse":"mouses.png",
	"NA":"NATUS.png",
	"Orange":"Orange1.png",
	"RS":"Rattlesnake.png",
	"Dignitas":"TeamDignitas.png",
	"Zenith":"TeamZenith.png",
	"TT":"Titan.png",
	"TF":"TongFu.png",
	"":""
}